### ISSUE TITLE
Continue numbering in items list

### ISSUE THREAD

**Issue by anermina** [metanorma/ogc-citygml2#11]
Numbering should continue regardless of subtitles appearing in some section. This applies to sections "9.7 Conformance requirements", "10.1.6 Conformance requirements", "10.2.6 Conformance requirements", "10.3.9 Conformance requirements", "10.5.8 Conformance requirements", "10.7.5 Conformance requirements", "10.11.3 Conformance requirements", "10.12.4 Conformance requirements" and all other cases where there is an attribute such as `[start=3]`.

Example:
![image](https://user-images.githubusercontent.com/55683568/151430658-66bdb708-2162-4fae-ab70-eaf869a81021.png)

_From https://github.com/opengeospatial/ogc-metanorma-testing/issues/74#issuecomment-1022337828_

**Comment by opoudjis** [comment]
As I have stated, we cannot support `start` in lists in a flavour with DOC in it without massive DOC HTML reengineering (https://github.com/metanorma/isodoc/issues/247: each list with a different start number needs its own custom CSS style), and I have declined to implement `start` outside of BSI (which has no DOC support).

I am very reluctant to implement this at this time, unless OGC is prepared to have HTML/PDF list numbering and DOC numbering out of sync.

**Comment by opoudjis** [comment]
@ghobona This is a legacy document, and custom formatting implementation is in our opinion a bad idea. It would be better to re-publish the CityGML 2 document with the updated format and then the Japanese translation.

**Comment by ghobona** [comment]
@opoudjis Ok, agreed. Comment withdrawn.
