### ISSUE TITLE
Enlarge figure 29

### ISSUE THREAD

**Issue by anermina** [metanorma/ogc-citygml2#12]
Figure 29 "Examples of buildings consisting of one and two building parts (source City of Coburg)" should be enlarged.

![image](https://user-images.githubusercontent.com/55683568/151430842-57824a82-2adb-4c4b-9139-c862f7d0ddcc.png)

_From https://github.com/opengeospatial/ogc-metanorma-testing/issues/74#issuecomment-1022337828_

**Comment by Intelligent2013** [comment]
@anermina the source image file https://github.com/metanorma/ogc-citygml2/blob/main/sources/images/058.gif has low quality -  416 x 171 pixels.

**Comment by anermina** [comment]
@Intelligent2013 you are right. I manually saved image from the original file, which resulted in better quality. Closing.
