### ISSUE TITLE
Verify structure and contents of document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/ogc-citygml2#3]
@anermina would you have time to double check the contents of the document?

I will check with the structure. Thanks!

_Originally posted by @ronaldtse in https://github.com/metanorma/ogc-citygml2/issues/1#issuecomment-1013633200_

**Comment by anermina** [comment]
Markup corrections are applied in https://github.com/metanorma/ogc-citygml2/pull/4.

**Comment by ronaldtse** [comment]
Done on my side too. Thanks @anermina !
