### ISSUE TITLE
Images inserted in the table are too small

### ISSUE THREAD

**Issue by anermina** [metanorma/ogc-citygml2#7]
Width of the images in the left-hand side column needs to be increased.

![image](https://user-images.githubusercontent.com/55683568/151430029-d8613459-e809-4021-a4e3-fe4535a27442.png)

_From https://github.com/opengeospatial/ogc-metanorma-testing/issues/74#issuecomment-1022337828_

**Comment by Intelligent2013** [comment]
@anermina looks like the screenshot relates to the word/html, but in PDF the logo rendered not well too:
![image](https://user-images.githubusercontent.com/5559926/151440619-8ab24585-c18c-4b05-a305-9e1343754889.png)


The issue in PDF can solved by setting width for table's columns like this:
```
[cols="1,4"]
```
Then the resulted PDF will be rendered so:
![image](https://user-images.githubusercontent.com/5559926/151441209-3ab3e76f-99a3-4c23-9751-16453d90150f.png)

**Comment by anermina** [comment]
I changed markup to `[cols="1,4"]` in #13 .

**Comment by opoudjis** [comment]
@anermina That addresses this issue, right? We can't really auto-format a solution here...

**Comment by manuelfuenmayor** [comment]
Images from HTML output look larger than before:

![issue1_html](https://user-images.githubusercontent.com/33627611/151999866-f13b0c27-1f8b-48b8-9168-010da971c7d9.PNG)

But I know if that would be enough...

On the other hand, images from doc output look as they should, in my opinion:

![issue1_doc](https://user-images.githubusercontent.com/33627611/152000111-c9d902a5-fc85-40e1-85c8-c53cc7723136.PNG)

**Comment by opoudjis** [comment]
The HTML is not respecting the colgroup markup of column width in the table rigidly: colgroup is saying the first column is 20%, but the HTML is allowing the second column to expand arbitrarily.

The fix, per https://stackoverflow.com/questions/13979239/width-of-table-cell-based-on-colgroup-not-working/17053247, is to add the CSS styling `table-layout: fixed;`, to maintain the proportion of the columns as their width  gets greater.
