### ISSUE TITLE
Add additional text to "Submitting organizations" section

### ISSUE THREAD

**Issue by anermina** [metanorma/ogc-citygml2#8]
"Submitting organizations" section has different intro and contains additional paragraph after the list of organizations.

![image](https://user-images.githubusercontent.com/55683568/151430250-960cdf71-efed-4f6f-9792-400da0a311c3.png)

_From https://github.com/opengeospatial/ogc-metanorma-testing/issues/74#issuecomment-1022337828_

**Comment by opoudjis** [comment]
The text being used for submitting organisations is hardcoded currently, and there is no provision to change it for different documents.

@ghobona This is a legacy document, and custom formatting implementation is in our opinion a bad idea. It would be better to re-publish the CityGML 2 document with the updated format and then the Japanese translation.

**Comment by opoudjis** [comment]
In line with the other related issues, closing this.
